name: Build KDE SDK Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak

      - name: Add Flathub Remote
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Download org.kde.Sdk 6.9
        run: |
          flatpak install --noninteractive --download-only flathub org.kde.Sdk//6.9

      - name: Create Flatpak Bundle
        run: |
          mkdir -p bundle
          flatpak build-bundle ~/.local/share/flatpak/repo bundle/org.kde.Sdk-6.9-x86_64.flatpak org.kde.Sdk 6.9

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: org.kde.Sdk-6.9-x86_64
          path: bundle/org.kde.Sdk-6.9-x86_64.flatpak
