name: Build KDE SDK Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak

      - name: Create unprivileged user
        run: |
          sudo useradd -m builder
          sudo chown -R builder:builder /home/builder

      - name: Download and bundle Flatpak as builder
        run: |
          sudo --login --user builder bash <<'EOF'
          set -e
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --user install --noninteractive --download-only flathub org.kde.Sdk//6.9
          mkdir -p ~/bundle
          flatpak build-bundle ~/.local/share/flatpak/repo ~/bundle/org.kde.Sdk-6.9-x86_64.flatpak org.kde.Sdk 6.9
          EOF

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: org.kde.Sdk-6.9-x86_64
          path: /home/builder/bundle/org.kde.Sdk-6.9-x86_64.flatpak
