name: Build KDE SDK Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak

      - name: Create unprivileged user
        run: |
          sudo useradd -m builder
          sudo chown -R builder:builder /home/builder

      - name: Run Flatpak commands as unprivileged user
        run: |
          sudo -u builder flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo -u builder flatpak --user install --noninteractive --download-only flathub org.kde.Sdk//6.9
          mkdir -p /home/builder/bundle
          sudo -u builder flatpak build-bundle /home/builder/.local/share/flatpak/repo /home/builder/bundle/org.kde.Sdk-6.9-x86_64.flatpak org.kde.Sdk 6.9
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: org.kde.Sdk-6.9-x86_64
          path: /home/builder/bundle/org.kde.Sdk-6.9-x86_64.flatpak
